In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
import seaborn as sns

In [5]:
train=pd.read_csv(r"C:\Users\pk859\OneDrive\Desktop\train.csv")

C:\Users\pk859\AppData\Local\Temp\ipykernel_36388\1281173683.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  train=pd.read_csv(r"C:\Users\pk859\OneDrive\Desktop\train.csv")

In [6]:
train.sample(20)

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue
244454,244455,Edgar,Illinois,US,17161,0.102559,2020-01-30,ConfirmedCases,0
609823,609824,Buncombe,North Carolina,US,261191,0.801731,2020-06-02,Fatalities,5
962443,962444,Weston,Wyoming,US,6927,1.130796,2020-03-04,Fatalities,0
197448,197449,Gwinnett,Georgia,US,936250,0.072729,2020-02-16,ConfirmedCases,0
549194,549195,Gosper,Nebraska,US,1990,0.131641,2020-03-20,ConfirmedCases,0
244484,244485,Edgar,Illinois,US,17161,0.102559,2020-02-14,ConfirmedCases,0
214540,214541,Stewart,Georgia,US,6621,0.113660,2020-02-22,ConfirmedCases,0
949366,949367,Polk,Wisconsin,US,43783,0.093571,2020-04-15,ConfirmedCases,0
459437,459438,Pope,Minnesota,US,11249,1.072027,2020-05-20,Fatalities,0
157268,157269,New London,Connecticut,US,265206,0.080075,2020-04-26,ConfirmedCases,25
843402,843403,Sabine,Texas,US,10542,0.107954,2020-02-13,ConfirmedCases,0
6082,6083,NaN,NaN,Bangladesh,161006790,0.052919,2020-05-03,ConfirmedCases,665
317375,317376,Taylor,Iowa,US,6121,1.146836,2020-03-30,Fatalities,0
727237,727238,Newport,Rhode Island,US,82082,0.883745,2020-03-01,Fatalities,0
300836,300837,Delaware,Iowa,US,17011,0.102652,2020-03-21,ConfirmedCases,0
472760,472761,Greene,Mississippi,US,13586,0.105077,2020-03-23,ConfirmedCases,0
661841,661842,Knox,Ohio,US,62322,0.905790,2020-05-02,Fatalities,0
364722,364723,Hart,Kentucky,US,19035,0.101481,2020-04-13,ConfirmedCases,0
165443,165444,Gilchrist,Florida,US,18582,1.017294,2020-05-23,Fatalities,0
248365,248366,Henry,Illinois,US,48913,0.926113,2020-01-25,Fatalities,0

In [7]:
test=pd.read_csv(r"C:\Users\pk859\OneDrive\Desktop\test.csv")

In [8]:
test

,ForecastId,County,Province_State,Country_Region,Population,Weight,Date,Target
0,1,NaN,NaN,Afghanistan,27657145,0.058359,2020-04-27,ConfirmedCases
1,2,NaN,NaN,Afghanistan,27657145,0.583587,2020-04-27,Fatalities
2,3,NaN,NaN,Afghanistan,27657145,0.058359,2020-04-28,ConfirmedCases
3,4,NaN,NaN,Afghanistan,27657145,0.583587,2020-04-28,Fatalities
4,5,NaN,NaN,Afghanistan,27657145,0.058359,2020-04-29,ConfirmedCases
...,...,...,...,...,...,...,...,...
311665,311666,NaN,NaN,Zimbabwe,14240168,0.607106,2020-06-08,Fatalities
311666,311667,NaN,NaN,Zimbabwe,14240168,0.060711,2020-06-09,ConfirmedCases
311667,311668,NaN,NaN,Zimbabwe,14240168,0.607106,2020-06-09,Fatalities
311668,311669,NaN,NaN,Zimbabwe,14240168,0.060711,2020-06-10,ConfirmedCases
311669,311670,NaN,NaN,Zimbabwe,14240168,0.607106,2020-06-10,Fatalities

In [9]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969640 entries, 0 to 969639
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Id              969640 non-null  int64
 1   County          880040 non-null  object
 2   Province_State  917280 non-null  object
 3   Country_Region  969640 non-null  object
 4   Population      969640 non-null  int64
 5   Weight          969640 non-null  float64
 6   Date            969640 non-null  object
 7   Target          969640 non-null  object
 8   TargetValue     969640 non-null  int64
dtypes: float64(1), int64(3), object(5)
memory usage: 66.6+ MB

In [10]:
train.describe()

                  Id    Population         Weight    TargetValue
count  969640.000000  9.696400e+05  969640.000000  969640.000000
mean   484820.500000  2.720127e+06       0.530870      12.563518
std    279911.101846  3.477771e+07       0.451909     302.524795
min         1.000000  8.600000e+01       0.047491  -10034.000000
25%    242410.750000  1.213300e+04       0.096838       0.000000
50%    484820.500000  3.053100e+04       0.349413       0.000000
75%    727230.250000  1.056120e+05       0.968379       0.000000
max    969640.000000  1.395773e+09       2.239186   36163.000000

In [11]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311670 entries, 0 to 311669
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ForecastId      311670 non-null  int64
 1   County          282870 non-null  object
 2   Province_State  294840 non-null  object
 3   Country_Region  311670 non-null  object
 4   Population      311670 non-null  int64
 5   Weight          311670 non-null  float64
 6   Date            311670 non-null  object
 7   Target          311670 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 19.0+ MB

In [12]:
train.isnull().sum()

Id                    0
County            89600
Province_State    52360
Country_Region        0
Population            0
Weight                0
Date                  0
Target                0
TargetValue           0
dtype: int64

In [13]:
test.isnull().sum()

ForecastId            0
County            28800
Province_State    16830
Country_Region        0
Population            0
Weight                0
Date                  0
Target                0
dtype: int64

In [14]:
for i in train.columns:
    print(f"unnique{i}'s count:{train[i].nunique()}")
    print(f"{train[i].unique()}\n")

unniqueId's count:969640
[     1      2      3 ... 969638 969639 969640]

unniqueCounty's count:1840
[nan 'Autauga' 'Baldwin' ... 'Uinta' 'Washakie' 'Weston']

unniqueProvince_State's count:133
[nan 'Australian Capital Territory' 'New South Wales' 'Northern Territory'
 'Queensland' 'South Australia' 'Tasmania' 'Victoria' 'Western Australia'
 'Alberta' 'British Columbia' 'Manitoba' 'New Brunswick'
 'Newfoundland and Labrador' 'Northwest Territories' 'Nova Scotia'
 'Ontario' 'Prince Edward Island' 'Quebec' 'Saskatchewan' 'Yukon' 'Anhui'
 'Beijing' 'Chongqing' 'Fujian' 'Gansu' 'Guangdong' 'Guangxi' 'Guizhou'
 'Hainan' 'Hebei' 'Heilongjiang' 'Henan' 'Hong Kong' 'Hubei' 'Hunan'
 'Inner Mongolia' 'Jiangsu' 'Jiangxi' 'Jilin' 'Liaoning' 'Macau' 'Ningxia'
 'Qinghai' 'Shaanxi' 'Shandong' 'Shanghai' 'Shanxi' 'Sichuan' 'Tianjin'
 'Tibet' 'Xinjiang' 'Yunnan' 'Zhejiang' 'Faroe Islands' 'Greenland'
 'French Guiana' 'French Polynesia' 'Guadeloupe' 'Martinique' 'Mayotte'
 'New Caledonia' 'Reunion' 'Saint Barthelemy' 'Saint Pierre and Miquelon'
 'St Martin' 'Aruba' 'Bonaire, Sint Eustatius and Saba' 'Curacao'
 'Sint Maarten' 'Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California'
 'Colorado' 'Connecticut' 'Delaware' 'District of Columbia' 'Florida'
 'Georgia' 'Guam' 'Hawaii' 'Idaho' 'Illinois' 'Indiana' 'Iowa' 'Kansas'
 'Kentucky' 'Louisiana' 'Maine' 'Maryland' 'Massachusetts' 'Michigan'
 'Minnesota' 'Mississippi' 'Missouri' 'Montana' 'Nebraska' 'Nevada'
 'New Hampshire' 'New Jersey' 'New Mexico' 'New York' 'North Carolina'
 'North Dakota' 'Ohio' 'Oklahoma' 'Oregon' 'Pennsylvania' 'Puerto Rico'
 'Rhode Island' 'South Carolina' 'South Dakota' 'Tennessee' 'Texas' 'Utah'
 'Vermont' 'Virgin Islands' 'Virginia' 'Washington' 'West Virginia'
 'Wisconsin' 'Wyoming' 'Anguilla' 'Bermuda' 'British Virgin Islands'
 'Cayman Islands' 'Channel Islands' 'Falkland Islands (Malvinas)'
 'Gibraltar' 'Isle of Man' 'Montserrat' 'Turks and Caicos Islands']

unniqueCountry_Region's count:187
['Afghanistan' 'Albania' 'Algeria' 'Andorra' 'Angola'
 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Australia' 'Austria'
 'Azerbaijan' 'Bahamas' 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus'
 'Belgium' 'Belize' 'Benin' 'Bhutan' 'Bolivia' 'Bosnia and Herzegovina'
 'Botswana' 'Brazil' 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burma' 'Burundi'
 'Cabo Verde' 'Cambodia' 'Cameroon' 'Canada' 'Central African Republic'
 'Chad' 'Chile' 'China' 'Colombia' 'Comoros' 'Congo (Brazzaville)'
 'Congo (Kinshasa)' 'Costa Rica' "Cote d'Ivoire" 'Croatia' 'Cuba' 'Cyprus'
 'Czechia' 'Denmark' 'Diamond Princess' 'Djibouti' 'Dominica'
 'Dominican Republic' 'Ecuador' 'Egypt' 'El Salvador' 'Equatorial Guinea'
 'Eritrea' 'Estonia' 'Eswatini' 'Ethiopia' 'Fiji' 'Finland' 'France'
 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Holy See'
 'Honduras' 'Hungary' 'Iceland' 'India' 'Indonesia' 'Iran' 'Iraq'
 'Ireland' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan' 'Kazakhstan'
 'Kenya' 'Korea, South' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia'
 'Lebanon' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania' 'Luxembourg'
 'MS Zaandam' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Mauritania' 'Mauritius' 'Mexico' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Morocco' 'Mozambique' 'Namibia' 'Nepal' 'Netherlands'
 'New Zealand' 'Nicaragua' 'Niger' 'Nigeria' 'North Macedonia' 'Norway'
 'Oman' 'Pakistan' 'Panama' 'Papua New Guinea' 'Paraguay' 'Peru'
 'Philippines' 'Poland' 'Portugal' 'Qatar' 'Romania' 'Russia' 'Rwanda'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Vincent and the Grenadines'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Senegal' 'Serbia'
 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovakia' 'Slovenia' 'Somalia'
 'South Africa' 'South Sudan' 'Spain' 'Sri Lanka' 'Sudan' 'Suriname'
 'Sweden' 'Switzerland' 'Syria' 'Taiwan*' 'Tajikistan' 'Tanzania'
 'Thailand' 'Timor-Leste' 'Togo' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'US' 'Uganda' 'Ukraine' 'United Arab Emirates' 'United Kingdom' 'Uruguay'
 'Uzbekistan' 'Venezuela' 'Vietnam' 'West Bank and Gaza' 'Western Sahara'
 'Yemen' 'Zambia' 'Zimbabwe']

unniquePopulation's count:3408
[27657145  2886026 40400000 ... 28500000 15933883 14240168]

unniqueWeight's count:6816
[0.05835874 0.58358737 0.06722512 ... 0.60299234 0.06071064 0.6071064 ]

unniqueDate's count:140
['2020-01-23' '2020-01-24' '2020-01-25' '2020-01-26' '2020-01-27'
 '2020-01-28' '2020-01-29' '2020-01-30' '2020-01-31' '2020-02-01'
 '2020-02-02' '2020-02-03' '2020-02-04' '2020-02-05' '2020-02-06'
 '2020-02-07' '2020-02-08' '2020-02-09' '2020-02-10' '2020-02-11'
 '2020-02-12' '2020-02-13' '2020-02-14' '2020-02-15' '2020-02-16'
 '2020-02-17' '2020-02-18' '2020-02-19' '2020-02-20' '2020-02-21'
 '2020-02-22' '2020-02-23' '2020-02-24' '2020-02-25' '2020-02-26'
 '2020-02-27' '2020-02-28' '2020-02-29' '2020-03-01' '2020-03-02'
 '2020-03-03' '2020-03-04' '2020-03-05' '2020-03-06' '2020-03-07'
 '2020-03-08' '2020-03-09' '2020-03-10' '2020-03-11' '2020-03-12'
 '2020-03-13' '2020-03-14' '2020-03-15' '2020-03-16' '2020-03-17'
 '2020-03-18' '2020-03-19' '2020-03-20' '2020-03-21' '2020-03-22'
 '2020-03-23' '2020-03-24' '2020-03-25' '2020-03-26' '2020-03-27'
 '2020-03-28' '2020-03-29' '2020-03-30' '2020-03-31' '2020-04-01'
 '2020-04-02' '2020-04-03' '2020-04-04' '2020-04-05' '2020-04-06'
 '2020-04-07' '2020-04-08' '2020-04-09' '2020-04-10' '2020-04-11'
 '2020-04-12' '2020-04-13' '2020-04-14' '2020-04-15' '2020-04-16'
 '2020-04-17' '2020-04-18' '2020-04-19' '2020-04-20' '2020-04-21'
 '2020-04-22' '2020-04-23' '2020-04-24' '2020-04-25' '2020-04-26'
 '2020-04-27' '2020-04-28' '2020-04-29' '2020-04-30' '2020-05-01'
 '2020-05-02' '2020-05-03' '2020-05-04' '2020-05-05' '2020-05-06'
 '2020-05-07' '2020-05-08' '2020-05-09' '2020-05-10' '2020-05-11'
 '2020-05-12' '2020-05-13' '2020-05-14' '2020-05-15' '2020-05-16'
 '2020-05-17' '2020-05-18' '2020-05-19' '2020-05-20' '2020-05-21'
 '2020-05-22' '2020-05-23' '2020-05-24' '2020-05-25' '2020-05-26'
 '2020-05-27' '2020-05-28' '2020-05-29' '2020-05-30' '2020-05-31'
 '2020-06-01' '2020-06-02' '2020-06-03' '2020-06-04' '2020-06-05'
 '2020-06-06' '2020-06-07' '2020-06-08' '2020-06-09' '2020-06-10']

unniqueTarget's count:2
['ConfirmedCases' 'Fatalities']

unniqueTargetValue's count:2603
[   0    1    3 ... 1650 1326  -21]

In [15]:
train.isnull().sum()/train.isnull().count()*100

Id                0.000000
County            9.240543
Province_State    5.399942
Country_Region    0.000000
Population        0.000000
Weight            0.000000
Date              0.000000
Target            0.000000
TargetValue       0.000000
dtype: float64

so our missing data is only 9% so we are going to delete the mising rows from our dataset becuase it will not affect our dataset
because missing dataset's values is lower than 10%

In [16]:
train.dropna(inplace=True)

In [17]:
train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 880040 entries, 67760 to 962639
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Id              880040 non-null  int64
 1   County          880040 non-null  object
 2   Province_State  880040 non-null  object
 3   Country_Region  880040 non-null  object
 4   Population      880040 non-null  int64
 5   Weight          880040 non-null  float64
 6   Date            880040 non-null  object
 7   Target          880040 non-null  object
 8   TargetValue     880040 non-null  int64
dtypes: float64(1), int64(3), object(5)
memory usage: 67.1+ MB

In [18]:
test.isnull().sum()/test.isnull().count()*100

ForecastId        0.000000
County            9.240543
Province_State    5.399942
Country_Region    0.000000
Population        0.000000
Weight            0.000000
Date              0.000000
Target            0.000000
dtype: float64

so, same here we are having null values around 9% so, we are going to drop these null values

In [19]:
test.dropna(inplace=True)

In [20]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 282870 entries, 21780 to 309419
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ForecastId      282870 non-null  int64
 1   County          282870 non-null  object
 2   Province_State  282870 non-null  object
 3   Country_Region  282870 non-null  object
 4   Population      282870 non-null  int64
 5   Weight          282870 non-null  float64
 6   Date            282870 non-null  object
 7   Target          282870 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 19.4+ MB

In [21]:
train["County"].value_counts()

Washington    8680
Jefferson     7280
Franklin      7000
Lincoln       6720
Jackson       6720
              ...
Harford        280
Garrett        280
Charles        280
Cecil          280
Weston         280
Name: County, Length: 1840, dtype: int64

In [22]:
train.groupby(["County"])["TargetValue"].mean().sort_values(ascending=False)

County
New York        821.707143
Los Angeles     249.567857
Westchester     126.696429
Cook            104.402381
Philadelphia     90.732143
                   ...
Weber             0.000000
Daniels           0.000000
Towner            0.000000
Mora              0.000000
Duchesne          0.000000
Name: TargetValue, Length: 1840, dtype: float64

In [32]:
train.groupby(["County"])["target1"].mean().sort_values(ascending=False)

County
Abbeville    0.5
Otsego       0.5
Otero        0.5
Oswego       0.5
Oscoda       0.5
            ...
Gallia       0.5
Gallatin     0.5
Galax        0.5
Gaines       0.5
Ziebach      0.5
Name: target1, Length: 1840, dtype: float64

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
tr=LabelEncoder()

In [28]:
train["country_tr"]=tr.fit_transform(train["County"])

In [29]:
train["province_state_tr"]=tr.fit_transform(train["Province_State"])

In [30]:
train["country_region_tr"]=tr.fit_transform(train["Country_Region"])

In [31]:
train["target1"]=tr.fit_transform(train["Target"])

In [33]:
train.sample(50)

,Id,County,Province_State,Country_Region,Population,Weight,Date,Target,TargetValue,country_tr,province_state_tr,country_region_tr,target1
743565,743566,Buffalo,South Dakota,US,1962,1.318873,2020-04-14,Fatalities,0,219,41,0,1
123317,123318,El Dorado,California,US,192843,0.821717,2020-03-21,Fatalities,0,532,4,0,1
869234,869235,Orange,Vermont,US,28892,0.097358,2020-03-20,ConfirmedCases,0,1225,45,0,0
154407,154408,Teller,Colorado,US,25388,0.985992,2020-03-26,Fatalities,0,1624,5,0,1
622222,622223,Macon,North Carolina,US,35858,0.095353,2020-02-23,ConfirmedCases,0,1005,33,0,0
202219,202220,Jones,Georgia,US,28735,0.974098,2020-02-21,Fatalities,0,842,10,0,1
643724,643725,Nelson,North Dakota,US,2879,0.125541,2020-01-25,ConfirmedCases,0,1156,34,0,0
706984,706985,Yamhill,Oregon,US,107100,0.086344,2020-06-03,ConfirmedCases,4,1821,37,0,0
406315,406316,Somerset,Maine,US,50484,0.923410,2020-02-09,Fatalities,0,1529,19,0,1
459322,459323,Pope,Minnesota,US,11249,0.107203,2020-03-24,ConfirmedCases,0,1320,23,0,0
841924,841925,Refugio,Texas,US,6948,0.113041,2020-05-24,ConfirmedCases,0,1380,43,0,0
553343,553344,Keya Paha,Nebraska,US,806,1.494026,2020-02-23,Fatalities,0,879,27,0,1
766009,766010,Decatur,Tennessee,US,11663,1.067890,2020-05-06,Fatalities,0,461,42,0,1
952225,952226,Sheboygan,Wisconsin,US,115340,0.857953,2020-05-14,Fatalities,0,1504,49,0,1
486616,486617,Tippah,Mississippi,US,22015,0.100005,2020-05-30,ConfirmedCases,2,1639,24,0,0
742179,742180,Bennett,South Dakota,US,3365,1.231303,2020-04-21,Fatalities,0,133,41,0,1
485233,485234,Smith,Mississippi,US,15916,1.033576,2020-06-07,Fatalities,0,1523,24,0,1
230616,230617,Clearwater,Idaho,US,8756,0.110161,2020-04-20,ConfirmedCases,0,347,12,0,0
640425,640426,Griggs,North Dakota,US,2231,1.296907,2020-02-24,Fatalities,0,686,34,0,1
300364,300365,Davis,Iowa,US,9000,0.109829,2020-05-04,ConfirmedCases,1,448,15,0,0
343100,343101,Republic,Kansas,US,4636,0.118458,2020-03-13,ConfirmedCases,0,1384,16,0,0
78234,78235,Lamar,Alabama,US,13805,0.104900,2020-03-20,ConfirmedCases,1,925,0,0,0
614727,614728,Davidson,North Carolina,US,167609,0.831297,2020-03-26,Fatalities,0,445,33,0,1
588805,588806,Valencia,New Mexico,US,76688,0.889085,2020-05-24,Fatalities,0,1695,31,0,1
472374,472375,George,Mississippi,US,24500,0.098947,2020-01-30,ConfirmedCases,0,627,24,0,0
478553,478554,Leflore,Mississippi,US,28183,0.975942,2020-02-08,Fatalities,0,955,24,0,1
891269,891270,Louisa,Virginia,US,37591,0.949258,2020-02-06,Fatalities,0,986,46,0,1
188343,188344,Coffee,Georgia,US,43273,0.936741,2020-04-23,Fatalities,0,362,10,0,1
812097,812098,Gray,Texas,US,21886,1.000636,2020-03-11,Fatalities,0,669,43,0,1
537301,537302,Toole,Montana,US,4736,1.181592,2020-06-01,Fatalities,0,1649,26,0,1
218225,218226,Troup,Georgia,US,69922,0.896447,2020-03-15,Fatalities,0,1666,10,0,1
612676,612677,Clay,North Carolina,US,11231,0.107221,2020-02-10,ConfirmedCases,0,343,33,0,0
851603,851604,Upton,Texas,US,3657,1.218818,2020-03-24,Fatalities,0,1690,43,0,1
453128,453129,Lake of the Woods,Minnesota,US,3740,0.121549,2020-03-07,ConfirmedCases,0,924,23,0,0
529160,529161,Jefferson,Montana,US,12221,0.106259,2020-05-22,ConfirmedCases,0,828,26,0,0
262704,262705,Stark,Illinois,US,5342,0.116502,2020-02-24,ConfirmedCases,0,1565,13,0,0
100435,100436,Baxter,Arkansas,US,41932,0.939512,2020-04-29,Fatalities,0,113,3,0,1
614092,614093,Currituck,North Carolina,US,27763,0.097737,2020-02-18,ConfirmedCases,0,428,33,0,0
101832,101833,Carroll,Arkansas,US,28380,0.097528,2020-04-28,ConfirmedCases,1,266,3,0,0
331965,331966,Harper,Kansas,US,5436,1.162658,2020-04-14,Fatalities,0,724,16,0,1
401806,401807,West Carroll,Louisiana,US,10830,0.107641,2020-01-26,ConfirmedCases,0,1759,18,0,0
808663,808664,Foard,Texas,US,1155,1.417892,2020-02-03,Fatalities,0,583,43,0,1
591653,591654,Clinton,New York,US,80485,0.885282,2020-01-29,Fatalities,0,352,32,0,1
618488,618489,Halifax,North Carolina,US,50010,0.092421,2020-05-26,ConfirmedCases,2,700,33,0,0
742792,742793,Brookings,South Dakota,US,35077,0.095554,2020-05-18,ConfirmedCases,0,206,41,0,0
338116,338117,Miami,Kansas,US,34237,0.095775,2020-04-10,ConfirmedCases,0,1085,16,0,0
208585,208586,Muscogee,Georgia,US,195769,0.820702,2020-06-03,Fatalities,0,1141,10,0,1
425815,425816,Genesee,Michigan,US,405813,0.774374,2020-05-09,Fatalities,9,624,22,0,1
418993,418994,Alcona,Michigan,US,10405,1.081065,2020-03-19,Fatalities,0,15,22,0,1
508232,508233,McDonald,Missouri,US,22837,0.099639,2020-02-08,ConfirmedCases,0,1050,25,0,0

In [34]:
test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 282870 entries, 21780 to 309419
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ForecastId      282870 non-null  int64
 1   County          282870 non-null  object
 2   Province_State  282870 non-null  object
 3   Country_Region  282870 non-null  object
 4   Population      282870 non-null  int64
 5   Weight          282870 non-null  float64
 6   Date            282870 non-null  object
 7   Target          282870 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 19.4+ MB

In [35]:
test["country_te"]=tr.fit_transform(test["County"])

In [36]:
test

,ForecastId,County,Province_State,Country_Region,Population,Weight,Date,Target,country_te
21780,21781,Autauga,Alabama,US,55869,0.091485,2020-04-27,ConfirmedCases,81
21781,21782,Autauga,Alabama,US,55869,0.914848,2020-04-27,Fatalities,81
21782,21783,Autauga,Alabama,US,55869,0.091485,2020-04-28,ConfirmedCases,81
21783,21784,Autauga,Alabama,US,55869,0.914848,2020-04-28,Fatalities,81
21784,21785,Autauga,Alabama,US,55869,0.091485,2020-04-29,ConfirmedCases,81
...,...,...,...,...,...,...,...,...,...
309415,309416,Weston,Wyoming,US,6927,1.130796,2020-06-08,Fatalities,1763
309416,309417,Weston,Wyoming,US,6927,0.113080,2020-06-09,ConfirmedCases,1763
309417,309418,Weston,Wyoming,US,6927,1.130796,2020-06-09,Fatalities,1763
309418,309419,Weston,Wyoming,US,6927,0.113080,2020-06-10,ConfirmedCases,1763
309419,309420,Weston,Wyoming,US,6927,1.130796,2020-06-10,Fatalities,1763

In [37]:
test["province_state_te"]=tr.fit_transform(test["Province_State"])

In [38]:
test["country_region_tr"]=tr.fit_transform(test["Country_Region"])

In [39]:
test

,ForecastId,County,Province_State,Country_Region,Population,Weight,Date,Target,country_te,province_state_te,country_region_tr
21780,21781,Autauga,Alabama,US,55869,0.091485,2020-04-27,ConfirmedCases,81,0,0
21781,21782,Autauga,Alabama,US,55869,0.914848,2020-04-27,Fatalities,81,0,0
21782,21783,Autauga,Alabama,US,55869,0.091485,2020-04-28,ConfirmedCases,81,0,0
21783,21784,Autauga,Alabama,US,55869,0.914848,2020-04-28,Fatalities,81,0,0
21784,21785,Autauga,Alabama,US,55869,0.091485,2020-04-29,ConfirmedCases,81,0,0
...,...,...,...,...,...,...,...,...,...,...,...
309415,309416,Weston,Wyoming,US,6927,1.130796,2020-06-08,Fatalities,1763,50,0
309416,309417,Weston,Wyoming,US,6927,0.113080,2020-06-09,ConfirmedCases,1763,50,0
309417,309418,Weston,Wyoming,US,6927,1.130796,2020-06-09,Fatalities,1763,50,0
309418,309419,Weston,Wyoming,US,6927,0.113080,2020-06-10,ConfirmedCases,1763,50,0
309419,309420,Weston,Wyoming,US,6927,1.130796,2020-06-10,Fatalities,1763,50,0

In [40]:
test["Target_te"]=tr.fit_transform(test["Target"])

In [41]:
test

,ForecastId,County,Province_State,Country_Region,Population,Weight,Date,Target,country_te,province_state_te,country_region_tr,Target_te
21780,21781,Autauga,Alabama,US,55869,0.091485,2020-04-27,ConfirmedCases,81,0,0,0
21781,21782,Autauga,Alabama,US,55869,0.914848,2020-04-27,Fatalities,81,0,0,1
21782,21783,Autauga,Alabama,US,55869,0.091485,2020-04-28,ConfirmedCases,81,0,0,0
21783,21784,Autauga,Alabama,US,55869,0.914848,2020-04-28,Fatalities,81,0,0,1
21784,21785,Autauga,Alabama,US,55869,0.091485,2020-04-29,ConfirmedCases,81,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
309415,309416,Weston,Wyoming,US,6927,1.130796,2020-06-08,Fatalities,1763,50,0,1
309416,309417,Weston,Wyoming,US,6927,0.113080,2020-06-09,ConfirmedCases,1763,50,0,0
309417,309418,Weston,Wyoming,US,6927,1.130796,2020-06-09,Fatalities,1763,50,0,1
309418,309419,Weston,Wyoming,US,6927,0.113080,2020-06-10,ConfirmedCases,1763,50,0,0
309419,309420,Weston,Wyoming,US,6927,1.130796,2020-06-10,Fatalities,1763,50,0,1

In [42]:
train.drop(["County"],axis=1,inplace=True)

In [43]:
train.drop(["Province_State"],axis=1,inplace=True)

In [44]:
train.drop(["Country_Region"],axis=1,inplace=True)

In [45]:
train.drop(["Target"],axis=1,inplace=True)

In [46]:
train.drop(["Date"],axis=1,inplace=True)

In [47]:
train

,Id,Population,Weight,TargetValue,country_tr,province_state_tr,country_region_tr,target1
67760,67761,55869,0.091485,0,81,0,0,0
67761,67762,55869,0.914848,0,81,0,0,1
67762,67763,55869,0.091485,0,81,0,0,0
67763,67764,55869,0.914848,0,81,0,0,1
67764,67765,55869,0.091485,0,81,0,0,0
...,...,...,...,...,...,...,...,...
962635,962636,6927,1.130796,0,1763,50,0,1
962636,962637,6927,0.113080,0,1763,50,0,0
962637,962638,6927,1.130796,0,1763,50,0,1
962638,962639,6927,0.113080,0,1763,50,0,0
962639,962640,6927,1.130796,0,1763,50,0,1

In [48]:
test.drop(["County"],axis=1,inplace=True)

In [49]:
test.drop(["Province_State"],axis=1,inplace=True)

In [50]:
test.drop(["Country_Region"],axis=1,inplace=True)

In [51]:
test.drop(["Target"],axis=1,inplace=True)

In [52]:
test.drop(["Date"],axis=1,inplace=True)

In [53]:
test

,ForecastId,Population,Weight,country_te,province_state_te,country_region_tr,Target_te
21780,21781,55869,0.091485,81,0,0,0
21781,21782,55869,0.914848,81,0,0,1
21782,21783,55869,0.091485,81,0,0,0
21783,21784,55869,0.914848,81,0,0,1
21784,21785,55869,0.091485,81,0,0,0
...,...,...,...,...,...,...,...
309415,309416,6927,1.130796,1763,50,0,1
309416,309417,6927,0.113080,1763,50,0,0
309417,309418,6927,1.130796,1763,50,0,1
309418,309419,6927,0.113080,1763,50,0,0
309419,309420,6927,1.130796,1763,50,0,1

In [54]:
x=train.iloc[:,-1].values.reshape(-1,1)

In [55]:
y=train["target1"]

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [58]:
from sklearn.neighbors import KNeighborsClassifier

In [59]:
knn=KNeighborsClassifier(n_neighbors=5)

In [60]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [61]:
from sklearn.metrics import accuracy_score

In [ ]:
acc_knn=round(knn.score(x_train,y_train)*100,2)

In [ ]:
acc_knn